# class User:
#     def __init__(self, userid, username):
#         self.id = userid
#         self.name = username
#         self.followers = 0
#         self.following = 0
#
#     def follow(self, user):
#         user.followers += 1
#         self.following += 1
#
# user_1 = User("001", "Jane")
# user_2 = User("002", "Jack")
#
# user_1.follow(user_2)
#
# print(user_1.followers)
# print(user_1.following)
# print(user_2.followers)
# print(user_2.following)

#================================

# more questions can be generated by API on "open Trivia database"

from question_model import Question
from data import question_data
from quiz_brain import QuizBrain

question_bank = []
for question in question_data:
    question_text = question["text"]
    question_answer = question["answer"]
    new_question = Question(question_text, question_answer)
    question_bank.append(new_question)

#print(question_bank[0].answer)

quiz = QuizBrain(question_bank)

while quiz.still_has_question():
    quiz.next_question()

print("You've completed the quiz")
print(f"Your final score was: {quiz.score}/{quiz.q_number}") # or {len(question_bank)}")

